version: '3'
services:
  ello-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ello-network


  ello-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - ello-network

networks:
  ello-network:
    driver: bridge
